### ISSUE TITLE
Improve the chooser modal following Wagtail's built-in ones

### ISSUE THREAD

**Issue by jeromelebleu** [wagtail/wagtail-generic-chooser#44]
Various cleaning and improvements have been made to choosers in Wagtail and should be included here - to satisfy the goal of covering all the functionality of built-in choosers.

What could be done at least is:
 * Clean up the JavaScript code of `chooser-modal.js` and make it more generic
 * Define separate views for results and creation form - as done in https://github.com/wagtail/wagtail/pull/7760 by @gasman. I could also help but it could be useful to state on the various actual mixins and the resulted ones. I guess maintainers and core developers of Wagtail have a better view on that.
 * Make the search form class customizable in order to add more filter fields - e.g. collection

**Comment by gasman** [comment]
Thanks @jeromelebleu! The eventual goal of my current chooser refactoring work is to extract a common base implementation that can serve as the basis of user-defined choosers as well as Wagtail's built-in ones, so wagtail-generic-chooser is very much tied in to that process. Really happy to hear that you're interested in helping out!

The new implementation will most likely live at `wagtail.admin.views.generic.chooser` and be some sort of hybrid of wagtail-generic-chooser and the refactored Wagtail chooser code, with the external wagtail-generic-chooser package becoming obsolete as a result. On that basis, bringing the two codebases closer together is definitely a good thing. However I suspect that it's going to be more efficient to do that within the Wagtail repo rather than this one, for a couple of reasons...

* The wagtail-generic-chooser package needs to stay compatible with existing releases of Wagtail, so we can't take advantage of improvements elsewhere in the Wagtail codebase - e.g. see https://github.com/wagtail/wagtail/pull/7769 where I made some extensions to the `wagtail.admin.ui.tables` code to fit the requirements of choosers. (If we were doing that within wagtail-generic-chooser, we'd have to wait for those extensions to make it into a Wagtail release...)
* We also need to consider backwards compatibility within wagtail-generic-chooser itself. In retrospect the "mixin soup" to handle the creation and results tabs as a single view was not a good architectural decision, and moving to separate views would be a big improvement - but then we need to provide an upgrade path for people who have already built things on top of the single-view pattern. We could always make a clean break and give it a major version bump to make it clear that people will need to update their code, but in that case we might as well consider `wagtail.admin.views.generic.chooser` to be the real "wagtail-generic-chooser 1.x".

**Comment by jeromelebleu** [comment]
Thanks @gasman for this detailed answer! Glad to know the plan of the future implementation, I didn't realize that it were on the way like that. I agree with you that it will be more efficient to work on the Wagtail repo directly.

I am now wondering if this proposal is still interesting regarding the backward incompatibility that it could introduce and the possible duplicated work with the Wagtail repo. I opened it and started to working on since the current state lack of a customizable search form and generic columns - as you did for the document and snippet choosers, wonderful! - for a project we are working on - [wagtail-webradio](https://forge.cliss21.org/cliss21/wagtail-webradio) which is in early stage. But instead of using wagtail-generic-chooser, we could just add a chooser view based on what you are doing for snippets and documents - in waiting for `wagtail.admin.views.generic.chooser`. I could then help if you need for the new implementation but I don't have the big picture yet, so I would probably need to be guided. What do you think?

**Comment by gasman** [comment]
Hi @jeromelebleu - can we interest you in joining the Wagtail core team? You've made plenty of really useful contributions to the project, and especially on these choosers your thoughts are very much aligned with the way we'd like to take them. It looks like I don't have contact details for you outside of Github, but if you're interested (no commitment yet, don't worry!) then please drop `tom@torchbox.com` an email.

**Comment by gasman** [comment]
Generic chooser viewsets are now implemented in Wagtail 4.0 and serve as the basis of the built-in choosers. https://docs.wagtail.org/en/stable/extending/generic_views.html#chooserviewset
